// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: proto/model/Mission.proto

package mission

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WinnerCondition int32

const (
	WinnerCondition_WINNER_CONDITION_INVALID               WinnerCondition = 0
	WinnerCondition_WINNER_CONDITION_REACH_TARGET_POSITION WinnerCondition = 1
	WinnerCondition_WINNER_CONDITION_DESTROY_ENEMY         WinnerCondition = 2
)

// Enum value maps for WinnerCondition.
var (
	WinnerCondition_name = map[int32]string{
		0: "WINNER_CONDITION_INVALID",
		1: "WINNER_CONDITION_REACH_TARGET_POSITION",
		2: "WINNER_CONDITION_DESTROY_ENEMY",
	}
	WinnerCondition_value = map[string]int32{
		"WINNER_CONDITION_INVALID":               0,
		"WINNER_CONDITION_REACH_TARGET_POSITION": 1,
		"WINNER_CONDITION_DESTROY_ENEMY":         2,
	}
)

func (x WinnerCondition) Enum() *WinnerCondition {
	p := new(WinnerCondition)
	*p = x
	return p
}

func (x WinnerCondition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WinnerCondition) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_model_Mission_proto_enumTypes[0].Descriptor()
}

func (WinnerCondition) Type() protoreflect.EnumType {
	return &file_proto_model_Mission_proto_enumTypes[0]
}

func (x WinnerCondition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WinnerCondition.Descriptor instead.
func (WinnerCondition) EnumDescriptor() ([]byte, []int) {
	return file_proto_model_Mission_proto_rawDescGZIP(), []int{0}
}

type PointType int32

const (
	PointType_POINT_TYPE_INVALID  PointType = 0
	PointType_POINT_TYPE_BLOCK    PointType = 1
	PointType_POINT_TYPE_POSITION PointType = 2
	PointType_POINT_TYPE_TARGET   PointType = 3
	PointType_POINT_TYPE_ENEMY    PointType = 4
)

// Enum value maps for PointType.
var (
	PointType_name = map[int32]string{
		0: "POINT_TYPE_INVALID",
		1: "POINT_TYPE_BLOCK",
		2: "POINT_TYPE_POSITION",
		3: "POINT_TYPE_TARGET",
		4: "POINT_TYPE_ENEMY",
	}
	PointType_value = map[string]int32{
		"POINT_TYPE_INVALID":  0,
		"POINT_TYPE_BLOCK":    1,
		"POINT_TYPE_POSITION": 2,
		"POINT_TYPE_TARGET":   3,
		"POINT_TYPE_ENEMY":    4,
	}
)

func (x PointType) Enum() *PointType {
	p := new(PointType)
	*p = x
	return p
}

func (x PointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PointType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_model_Mission_proto_enumTypes[1].Descriptor()
}

func (PointType) Type() protoreflect.EnumType {
	return &file_proto_model_Mission_proto_enumTypes[1]
}

func (x PointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PointType.Descriptor instead.
func (PointType) EnumDescriptor() ([]byte, []int) {
	return file_proto_model_Mission_proto_rawDescGZIP(), []int{1}
}

type Mission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Version   int64           `protobuf:"varint,2,opt,name=version,proto3" json:"version"`
	Condition WinnerCondition `protobuf:"varint,11,opt,name=condition,proto3,enum=CompetitionPlatform.proto.model.WinnerCondition" json:"condition"`
	Points    []*Point        `protobuf:"bytes,12,rep,name=points,proto3" json:"points"`
}

func (x *Mission) Reset() {
	*x = Mission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_Mission_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission) ProtoMessage() {}

func (x *Mission) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_Mission_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission.ProtoReflect.Descriptor instead.
func (*Mission) Descriptor() ([]byte, []int) {
	return file_proto_model_Mission_proto_rawDescGZIP(), []int{0}
}

func (x *Mission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Mission) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Mission) GetCondition() WinnerCondition {
	if x != nil {
		return x.Condition
	}
	return WinnerCondition_WINNER_CONDITION_INVALID
}

func (x *Mission) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type PointType `protobuf:"varint,1,opt,name=type,proto3,enum=CompetitionPlatform.proto.model.PointType" json:"type"`
	X    uint32    `protobuf:"varint,2,opt,name=x,proto3" json:"x"`
	Y    uint32    `protobuf:"varint,3,opt,name=y,proto3" json:"y"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_Mission_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_Mission_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_proto_model_Mission_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetType() PointType {
	if x != nil {
		return x.Type
	}
	return PointType_POINT_TYPE_INVALID
}

func (x *Point) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_proto_model_Mission_proto protoreflect.FileDescriptor

var file_proto_model_Mission_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x4d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x43, 0x6f, 0x6d,
	0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0xc3, 0x01, 0x0a,
	0x07, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x4e, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x30, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x3e, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x0c, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x22, 0x63, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x3e, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x43, 0x6f, 0x6d, 0x70,
	0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x79, 0x2a, 0x7f, 0x0a, 0x0f, 0x57, 0x69, 0x6e, 0x6e, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x18, 0x57, 0x49,
	0x4e, 0x4e, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x49,
	0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x2a, 0x0a, 0x26, 0x57, 0x49, 0x4e, 0x4e,
	0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x41,
	0x43, 0x48, 0x5f, 0x54, 0x41, 0x52, 0x47, 0x45, 0x54, 0x5f, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x49,
	0x4f, 0x4e, 0x10, 0x01, 0x12, 0x22, 0x0a, 0x1e, 0x57, 0x49, 0x4e, 0x4e, 0x45, 0x52, 0x5f, 0x43,
	0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x45, 0x53, 0x54, 0x52, 0x4f, 0x59,
	0x5f, 0x45, 0x4e, 0x45, 0x4d, 0x59, 0x10, 0x02, 0x2a, 0x7f, 0x0a, 0x09, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a,
	0x10, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x4c, 0x4f, 0x43,
	0x4b, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11,
	0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x41, 0x52, 0x47, 0x45,
	0x54, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x45, 0x4e, 0x45, 0x4d, 0x59, 0x10, 0x04, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x61, 0x6e, 0x73, 0x6e, 0x6f, 0x77, 0x2f,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_model_Mission_proto_rawDescOnce sync.Once
	file_proto_model_Mission_proto_rawDescData = file_proto_model_Mission_proto_rawDesc
)

func file_proto_model_Mission_proto_rawDescGZIP() []byte {
	file_proto_model_Mission_proto_rawDescOnce.Do(func() {
		file_proto_model_Mission_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_model_Mission_proto_rawDescData)
	})
	return file_proto_model_Mission_proto_rawDescData
}

var file_proto_model_Mission_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_model_Mission_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_model_Mission_proto_goTypes = []interface{}{
	(WinnerCondition)(0), // 0: CompetitionPlatform.proto.model.WinnerCondition
	(PointType)(0),       // 1: CompetitionPlatform.proto.model.PointType
	(*Mission)(nil),      // 2: CompetitionPlatform.proto.model.Mission
	(*Point)(nil),        // 3: CompetitionPlatform.proto.model.Point
}
var file_proto_model_Mission_proto_depIdxs = []int32{
	0, // 0: CompetitionPlatform.proto.model.Mission.condition:type_name -> CompetitionPlatform.proto.model.WinnerCondition
	3, // 1: CompetitionPlatform.proto.model.Mission.points:type_name -> CompetitionPlatform.proto.model.Point
	1, // 2: CompetitionPlatform.proto.model.Point.type:type_name -> CompetitionPlatform.proto.model.PointType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_model_Mission_proto_init() }
func file_proto_model_Mission_proto_init() {
	if File_proto_model_Mission_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_model_Mission_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_Mission_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_model_Mission_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_Mission_proto_goTypes,
		DependencyIndexes: file_proto_model_Mission_proto_depIdxs,
		EnumInfos:         file_proto_model_Mission_proto_enumTypes,
		MessageInfos:      file_proto_model_Mission_proto_msgTypes,
	}.Build()
	File_proto_model_Mission_proto = out.File
	file_proto_model_Mission_proto_rawDesc = nil
	file_proto_model_Mission_proto_goTypes = nil
	file_proto_model_Mission_proto_depIdxs = nil
}
