// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: proto/api/StartGame.proto

package start_game

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GameMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameMsg) Reset() {
	*x = GameMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_StartGame_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMsg) ProtoMessage() {}

func (x *GameMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_StartGame_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMsg.ProtoReflect.Descriptor instead.
func (*GameMsg) Descriptor() ([]byte, []int) {
	return file_proto_api_StartGame_proto_rawDescGZIP(), []int{0}
}

type GameMsg_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MainLogicFunc string `protobuf:"bytes,2,opt,name=main_logic_func,json=mainLogicFunc,proto3" json:"main_logic_func,omitempty"`
	AttackedFunc  string `protobuf:"bytes,3,opt,name=attacked_func,json=attackedFunc,proto3" json:"attacked_func,omitempty"`
	CrashFunc     string `protobuf:"bytes,4,opt,name=crash_func,json=crashFunc,proto3" json:"crash_func,omitempty"`
	DiscoverFunc  string `protobuf:"bytes,5,opt,name=discover_func,json=discoverFunc,proto3" json:"discover_func,omitempty"`
}

func (x *GameMsg_Request) Reset() {
	*x = GameMsg_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_StartGame_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameMsg_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMsg_Request) ProtoMessage() {}

func (x *GameMsg_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_StartGame_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMsg_Request.ProtoReflect.Descriptor instead.
func (*GameMsg_Request) Descriptor() ([]byte, []int) {
	return file_proto_api_StartGame_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GameMsg_Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GameMsg_Request) GetMainLogicFunc() string {
	if x != nil {
		return x.MainLogicFunc
	}
	return ""
}

func (x *GameMsg_Request) GetAttackedFunc() string {
	if x != nil {
		return x.AttackedFunc
	}
	return ""
}

func (x *GameMsg_Request) GetCrashFunc() string {
	if x != nil {
		return x.CrashFunc
	}
	return ""
}

func (x *GameMsg_Request) GetDiscoverFunc() string {
	if x != nil {
		return x.DiscoverFunc
	}
	return ""
}

type GameMsg_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameMsg_Response) Reset() {
	*x = GameMsg_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_StartGame_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameMsg_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMsg_Response) ProtoMessage() {}

func (x *GameMsg_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_StartGame_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMsg_Response.ProtoReflect.Descriptor instead.
func (*GameMsg_Response) Descriptor() ([]byte, []int) {
	return file_proto_api_StartGame_proto_rawDescGZIP(), []int{0, 1}
}

var File_proto_api_StartGame_proto protoreflect.FileDescriptor

var file_proto_api_StartGame_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x47, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x43, 0x6f, 0x6d,
	0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x22, 0xc2, 0x01, 0x0a, 0x07, 0x47,
	0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x1a, 0xaa, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x63,
	0x5f, 0x66, 0x75, 0x6e, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6d, 0x61, 0x69,
	0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x46, 0x75, 0x6e, 0x63, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x74,
	0x74, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x46, 0x75, 0x6e, 0x63, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x61, 0x73, 0x68, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x61, 0x73, 0x68, 0x46, 0x75, 0x6e, 0x63, 0x12, 0x23,
	0x0a, 0x0d, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x46,
	0x75, 0x6e, 0x63, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0x7b, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x6e, 0x0a, 0x09,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x2e, 0x43, 0x6f, 0x6d, 0x70,
	0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x73,
	0x67, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x43, 0x6f, 0x6d, 0x70,
	0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x73,
	0x67, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x3a, 0x5a, 0x38,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x61, 0x6e, 0x73, 0x6e,
	0x6f, 0x77, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_api_StartGame_proto_rawDescOnce sync.Once
	file_proto_api_StartGame_proto_rawDescData = file_proto_api_StartGame_proto_rawDesc
)

func file_proto_api_StartGame_proto_rawDescGZIP() []byte {
	file_proto_api_StartGame_proto_rawDescOnce.Do(func() {
		file_proto_api_StartGame_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_api_StartGame_proto_rawDescData)
	})
	return file_proto_api_StartGame_proto_rawDescData
}

var file_proto_api_StartGame_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_api_StartGame_proto_goTypes = []interface{}{
	(*GameMsg)(nil),          // 0: CompetitionPlatform.proto.api.GameMsg
	(*GameMsg_Request)(nil),  // 1: CompetitionPlatform.proto.api.GameMsg.Request
	(*GameMsg_Response)(nil), // 2: CompetitionPlatform.proto.api.GameMsg.Response
}
var file_proto_api_StartGame_proto_depIdxs = []int32{
	1, // 0: CompetitionPlatform.proto.api.StartGame.StartGame:input_type -> CompetitionPlatform.proto.api.GameMsg.Request
	2, // 1: CompetitionPlatform.proto.api.StartGame.StartGame:output_type -> CompetitionPlatform.proto.api.GameMsg.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_api_StartGame_proto_init() }
func file_proto_api_StartGame_proto_init() {
	if File_proto_api_StartGame_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_api_StartGame_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_StartGame_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameMsg_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_StartGame_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameMsg_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_api_StartGame_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_StartGame_proto_goTypes,
		DependencyIndexes: file_proto_api_StartGame_proto_depIdxs,
		MessageInfos:      file_proto_api_StartGame_proto_msgTypes,
	}.Build()
	File_proto_api_StartGame_proto = out.File
	file_proto_api_StartGame_proto_rawDesc = nil
	file_proto_api_StartGame_proto_goTypes = nil
	file_proto_api_StartGame_proto_depIdxs = nil
}
